// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdzXp6cSIh_spw3PES55uT4NtMerp74w4',
    appId: '1:202575584342:web:cacefa2e9ea841be106ff7',
    messagingSenderId: '202575584342',
    projectId: 'chat-5c87a',
    authDomain: 'chat-5c87a.firebaseapp.com',
    storageBucket: 'chat-5c87a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdcQHKb6gcXC3zW6B_t2y_m3taounvwjI',
    appId: '1:202575584342:android:1e5aab32306ff714106ff7',
    messagingSenderId: '202575584342',
    projectId: 'chat-5c87a',
    storageBucket: 'chat-5c87a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGBm6QCecPFSPUuq1R5pQjPyWipjAyRZ0',
    appId: '1:202575584342:ios:bbac7639cb830623106ff7',
    messagingSenderId: '202575584342',
    projectId: 'chat-5c87a',
    storageBucket: 'chat-5c87a.appspot.com',
    androidClientId: '202575584342-j9m59v97siq45t1589r8j40sqf139iu2.apps.googleusercontent.com',
    iosClientId: '202575584342-dfr1rpseot3of1ivdflckfehmgoqi92u.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGBm6QCecPFSPUuq1R5pQjPyWipjAyRZ0',
    appId: '1:202575584342:ios:bbac7639cb830623106ff7',
    messagingSenderId: '202575584342',
    projectId: 'chat-5c87a',
    storageBucket: 'chat-5c87a.appspot.com',
    androidClientId: '202575584342-j9m59v97siq45t1589r8j40sqf139iu2.apps.googleusercontent.com',
    iosClientId: '202575584342-dfr1rpseot3of1ivdflckfehmgoqi92u.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdzXp6cSIh_spw3PES55uT4NtMerp74w4',
    appId: '1:202575584342:web:35c9951390edddfc106ff7',
    messagingSenderId: '202575584342',
    projectId: 'chat-5c87a',
    authDomain: 'chat-5c87a.firebaseapp.com',
    storageBucket: 'chat-5c87a.appspot.com',
  );

}